config/routes.rb
require 'sidekiq/web'

Putne::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Sidekiq::Web, at: "/sidekiq"
  devise_for :users

  root "main#index"
  get "help" => "main#help"

  resources :users do
    get "secret_key" => "secret_key#index"
    post "secret_key/reset"
  end

  resources :projects do
    post "api/hook" => "commit_hook#hook"
    get "api/hook_url" => "commit_hook#hook_url"
    get "branches" => "git#branches"
    get "commits" => "git#commits"
    get "committers" => "git#committers"
    get "settings"
    get "create_all_reports"

    resources :reports do
      get "files" => "metrics#files"
      get "file" => "metrics#file"
      
      get "classes" => "metrics#classes"
      get "klass" => "metrics#klass"
      get "klass/:class_id" => "metrics#klass"

      get "methods" => "metrics#methods"
      get "method" => "metrics#method"

      get "churn" => "metrics#churn"
      get "complexity" => "metrics#complexity"
      get "duplicity" => "metrics#duplicity"
      get "smells" => "metrics#smells"
      get "smell" => "metrics#smell"

      get "timeline" => "metrics#timeline"
    end

    namespace :graph do
      get "sunburst_chart" => "projects#sunburst_chart"
      get "class_donut_chart" => "projects#class_donut_chart"
      get "git_dates" => "git#dates"
      get "stats_line_chart" => "projects#stats_line_chart"
      get "smell_pie_chart" => "projects#smell_pie_chart"
      get "smell_klass_chart" => "projects#smell_klass_pie_chart"
    end
  end

  

end

app/controllers/metrics_controller.rb
require 'parser/current'

class MetricsController < ApplicationController
  load_and_authorize_resource class: Project
  layout "layouts/sidebar"

  def files
    @title = "Files"
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])
    @files = @report.target_files.page(params[:page]).per(25)
  end

  def file
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])
    
    file_name = TargetFile.find(params[:file_id]).path
    @file = (@project.repository.git.last_commit.tree / file_name).data

    @title = "File viewer - #{file_name}"
  end
  
  def classes
    @title = "Classes"
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])
    @classes = @report.target_classes.page(params[:page]).per(25)
  end

  def klass
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])

    @class = TargetClass.find(params[:class_id])
    file_name = @class.target_file.path

    @file = (@project.repository.git.last_commit.tree / file_name).data
    #@file = @project.repository.git.blob(@report.commit.commit_hash, file_name).data
    
    @title = "Class viewer - #{file_name}"
  end
  
  def methods
    @title = "Methods"
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])
    @methods = @report.target_methods.page(params[:page]).per(25)
  end

  def method
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])

    method = TargetMethod.find(params[:method_id])

    if method.name =~ /#/
      method_name = method.name.split('#')[1]
    else
      method_name = method.name.split('::')[-1]
    end
    
    file_name = TargetMethod.find(params[:method_id]).target_class.target_file.path
    file = (@project.repository.git.last_commit.tree / file_name).data

    @method = ""
    @method_name = method_name
    find_source_code file, method_name

    @title = "Method vierew - #{@method_name}"
  end
  
  def churn
    @title = "Churns"
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])
  end

  def complexity
    @title = "Complexities"
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])
    @methods = @report.target_methods.page(params[:page]).per(25)
  end

  def duplicity
    @title = "Duplications"
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])
  end

  def smells
    @title = "Smells"
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])
    @smells = @report.smells.includes(:targetable).reeks.page(params[:page]).per(25)
  end

  def smell
    @title = "Smell"
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id]).includes(:smells)
  end

  def timeline
    @titmle = "Timeline"
    @project = Project.find(params[:project_id])
    @report = Report.find(params[:report_id])
  end

  private
  def find_source_code(file, method_name)
    ast_root = Parser::CurrentRuby.parse(file)
    recursive_search_ast(ast_root, method_name)
  end

  def recursive_search_ast(ast, name)
    ast.children.each do |child|
      if child.class.to_s == "Parser::AST::Node"
        if (child.type.to_s == "def" or child.type.to_s == "defs") and (child.children[0].to_s == name or child.children[1].to_s == name)
          @method = child.source_map.expression.to_source
          return 
        else
          recursive_search_ast(child, name)
        end
      end
    end
  end
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/metrics/churn.html.haml
.panel-heading
  %h1 
    %i.icon-copy
    = @project.title
    Duplications
.list-group
  .list-group-item
    %h4 File churns
  .list-group-item
    #file-churn-icecle
  .list-group-item
    %table.table.table-striped.churn
      %th.name File path
      %th.times Times changed
      - @report.scores.file_churns.each do |churn|
        %tr
          %td= link_to churn.targetable.path, project_report_file_path(@project, @report, file_id: churn.targetable)
          %td= churn.score

  -# .list-group-item
  -#   %h4 Class churns
  -# .list-group-item
  -#   %img{src: "/images/horison_sunbrust.jpg", style: "width: 100%;"}    
  -# .list-group-item
  -#   %table.table.table-striped.churn
  -#     %th.name Class name
  -#     %th.times Times changed
  -#     - @report.scores.class_churns.each do |churn|
  -#       %tr
  -#         %td= churn.targetable.name
  -#         %td= churn.score

  -# .list-group-item
  -#   %h4 Method churns
  -# .list-group-item
  -#   %img{src: "/images/horison_sunbrust.jpg", style: "width: 100%;"}    
  -# .list-group-item
  -#   %table.table.table-striped.churn
  -#     %th.name Method name
  -#     %th.times Times changed
  -#     - @report.scores.method_churns.each do |churn|
  -#       %tr
  -#         %td= churn.targetable.name
  -#         %td= churn.score

:javascript
  $(function(){
    //d3_multi_line_chart("#file-churn-icecle");
    d3_icecle_chart("#file-churn-icecle");
  });

app/views/metrics/classes.html.haml
.panel-heading
  %h1 
    %i.icon-inbox
    = @project.title
    Classes
.list-group
  .list-group-item
    .row
      .text-center
        %strong Filter
        LOC
        = "/"
        Complexities
        = "/"
        Smells
        = "/"
        Duplications
        = "/"
        Churns
        = "/"
        Bugspots
      .col-lg-12.col-mg-12.col-sm-12
        = render partial: "report_module/project_sunburst", locals: { project: @project }
  %h4.list-group-item Listing classes
  .list-group-item
    %table.table.table-striped{style: "width: 100%"}
      %tr
        %th Class name
        %th LOC
        %th Complexity
        %th Smells
        %th Duplications
        %th Churn
      - @classes.each do |klass|
        %tr
          %td= link_to klass.name, project_report_klass_path(@project, @report, class_id: klass)
          %td= rand(150) 
          %td= rand(150) 
          %td= rand(150) 
          %td= rand(150) 
          %td= rand(150) 
    = paginate(@classes)

app/views/metrics/complexity.html.haml
.panel-heading
  %h1 
    %i.icon-superscript
    = @project.title
    Complexity
.list-group
  .list-group-item
    #complexity-line-chart
  .list-group-item
    .row
      .col-lg-4.col-md-4.col-sm-4
        %h4 Class complexity rank
      .col-lg-4.col-md-4.col-sm-4
        %h4 C/M complexity rank
      .col-lg-4.col-md-4.col-sm-4
        %h4 Method complexity rank
  .list-group-item
    .row
      .col-lg-4.col-md-4.col-sm-4
        %table.table.table-striped
          %tr
            %th 1.
            %td Git
          %tr
            %th 2.
            %td Report
          %tr
            %th 3. 
            %td ReportCreator
      .col-lg-4.col-md-4.col-sm-4
        %table.table.table-striped
          %tr
            %th 1.
            %td Git
          %tr
            %th 2.
            %td Report
          %tr
            %th 3. 
            %td ReportCreator
      .col-lg-4.col-md-4.col-sm-4
        %table.table.table-striped
          %tr
            %th 1.
            %td Git#report
          %tr
            %th 2.
            %td Report#git
          %tr
            %th 3. 
            %td ReportCreator#hello
  .list-group-item
    %h4 Listing Complex ( classes, methods )
  .list-group-item
    %table.table.table.striped{style: "width: 100%;"}
      %th Methods
      %th Lines
      %th Flog score
      %th Saikiro score
      - @methods.each do |method|
        %tr
          %td= link_to method.name, project_report_method_path(@project, @report, method_id: method)
          -# %td= method.complexity_score.lines unless method.complexity_score.nil?
          -# %td= method.complexity_score.flog_score unless method.complexity_score.nil?
          -# %td= method.complexity_score.saikuro_score unless method.complexity_score.nil?
          #TODO
          %td= method.scores.locs[0].score unless method.scores.locs.empty?
          %td= method.scores.flogs[0].score unless method.scores.flogs.empty?
          %td= method.scores.saikuros[0].score unless method.scores.saikuros.empty?
    = paginate @methods

:javascript
  $(function(){
    d3_multi_line_chart("#complexity-line-chart", "#{project_graph_stats_line_chart_path(project_id: @project, columns: 'date,Complexity')}");
  });

app/views/metrics/duplicity.html.haml
.panel-heading
  %h1 
    %i.icon-copy
    = @project.title
    Duplications
.list-group
  .list-group-item
    #duplication-line-chart
  .list-group-item
    %img{src: "/images/horison_sunbrust.jpg", style: "width: 100%;"}    
  .list-group-item
    - @report.duplications.each_with_index do |duplication, index|
      %h4.list-group-item= "Duplication ##{index + 1}"

      %table.table.table-striped
        %th{style: "width: 65%;"} File path
        %th{style: "width: 35%;"} Line
        - duplication.file_line_infos.each do |line|
          %tr
            %td= line.target_file.path
            %td= line.line_num

:javascript
  $(function(){
    d3_multi_line_chart("#duplication-line-chart", "#{project_graph_stats_line_chart_path(project_id: @project, columns: 'date,Duplication')}");
  });

app/views/metrics/file.html.haml
= CodeRay.scan(@file, :ruby).div.html_safe

app/views/metrics/files.html.haml
%table.table.table-striped
  %th File Path
  %th Lines
  %th Complexity
  - @files.each do |file|
    - content = (@project.repository.git.last_commit.tree / file.path).data
    %tr
      %td= link_to file.path, project_report_file_path(@project, @report, file_id: file)
      %td= content.lines.count
      %td
= paginate(@files)

app/views/metrics/klass.html.haml
.panel-heading
  %h1 
    %i.icon-inbox
    = @class.name
.list-group
  -# .list-group-item
  -#   .row
  -#     .col-lg-12.col-md-12.col-sm-12
  -#       %img{src: "/images/horison_sunbrust.jpg", style: "width: 100%;"}
  -# .list-group-item
  -#   .row
  -#     .col-lg-9.col-md-9.col-sm-9
  -#       %h4 Complexity
  -#     .col-lg-3.col-md-3.col-sm-3
  -#       %h4 Map
  -# .list-group-item
  -#   .row
  -#     .col-lg-9.col-md-9.col-sm-9
  -#       %img{src: "/images/line_one_chart.png", style: "width: 100%;"}
  -#     .col-lg-3.col-md-3.col-sm-3
  -#       %img{src: "/images/donut_chart.png", style: "width: 100%;"}
  .list-group-item
    .row
      .col-lg-9.col-md-9.col-sm-9
        %h4 Source Code
      .col-lg-3.col-md-3.col-sm-3
        %h4 Index
  .list-group-item
    .row
      .col-lg-12.col-md-12.col-sm-12
        = CodeRay.scan(@file, :ruby).div.html_safe

app/views/metrics/method.html.haml
%h3= @method_name
= CodeRay.scan("  "+ @method, :ruby).div.html_safe

app/views/metrics/methods.html.haml
%table.table.table-striped
  %th Methods
  - @methods.each do |method|
    %tr
      %td= link_to method.name, project_report_method_path(@project, @report, method_id: method)
= paginate(@methods)

app/views/metrics/report.html.haml
- @project.reports.each do |report|
  = report.created_at
  %br/

app/views/metrics/smell.html.haml
.panel-heading
  %h1 
    %i.icon-bug
    = @project.title
    Smell : Smell name
.list-group
  .list-group-item
    %img{src: "/images/line_one_chart.png"}
  .list-group-item
    %img{src: "/images/horison_sunbrust.jpg", style: "width: 100%;"}    
  .list-group-item
    smell listing

app/views/metrics/smells.html.haml
.panel-heading
  %h1 
    %i.icon-bug
    = @project.title
    Smells
.list-group
  .list-group-item
    %ul.nav.nav-tabs
      %li.active
        %a{href: "#smell-donut", "data-toggle" => "tab"} Smell
      %li
        %a{href: "#class-smell-donut", "data-toggle" => "tab"} Class-Smell
  .tab-content
    .tab-pane.active#smell-donut
      %div{id: "#{@project.title}-smell-donut"}
    .tab-pane#class-smell-donut
      %div{id: "#{@project.title}-class-smell-donut"}
  -# .list-group-item
  -#   %h4 Class - Smells Graph
  -# .list-group-item
  -#   %img{src: "/images/horison_sunbrust.jpg", style: "width: 100%;"}    
  .list-group-item
    .row
      .col-lg-9.col-md-9.col-sm-9
        %h4 Listing smells
      .col-lg-3.col-md-3.col-sm-3
        %h4 Slophgraph
  .list-group-item
    .row
      .col-lg-12.col-md-12.col-sm-12
        %table.table.table-striped{style: "width: 100%;"}
          %th Method name
          %th Small type
          -#%th Message
          - @smells.each do |smell|
            %tr
              %td= smell.targetable.name
              %td= smell.smell
              -#%td= smell.message

        -# %table{style: "width: 100%;"}
        -#   %th File path
        -#   %th Line num
        -#   %th Message
        -#   - @report.roodis.each do |roodi|
        -#     %tr
        -#       %td= roodi.file_line_info.target_file.path
        -#       %td= roodi.file_line_info.line_num
        -#       %td= roodi.message
    = paginate @smells

:javascript
  $(function(){
    // d3_donut_chart("##{ @project.title + "-class-donut"}", "#{ project_graph_class_donut_chart_path(project_id: @project) }")
    d3_pie_chart("##{ @project.title + "-smell-donut"}", "#{ project_graph_smell_pie_chart_path(project_id: @project) }")
    d3_pie_chart("##{ @project.title + "-class-smell-donut"}", "#{ project_graph_smell_klass_chart_path(project_id: @project) }")
  });