config/routes.rb
require 'sidekiq/web'

Putne::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Sidekiq::Web, at: "/sidekiq"
  devise_for :users

  root "main#index"
  get "help" => "main#help"

  resources :users do
    get "secret_key" => "secret_key#index"
    post "secret_key/reset"
  end

  resources :projects do
    post "api/hook" => "commit_hook#hook"
    get "api/hook_url" => "commit_hook#hook_url"
    get "branches" => "git#branches"
    get "commits" => "git#commits"
    get "committers" => "git#committers"
    get "settings"
    get "create_all_reports"

    resources :reports do
      get "files" => "metrics#files"
      get "file" => "metrics#file"
      
      get "classes" => "metrics#classes"
      get "klass" => "metrics#klass"
      get "klass/:class_id" => "metrics#klass"

      get "methods" => "metrics#methods"
      get "method" => "metrics#method"

      get "churn" => "metrics#churn"
      get "complexity" => "metrics#complexity"
      get "duplicity" => "metrics#duplicity"
      get "smells" => "metrics#smells"
      get "smell" => "metrics#smell"

      get "timeline" => "metrics#timeline"
    end

    namespace :graph do
      get "sunburst_chart" => "projects#sunburst_chart"
      get "class_donut_chart" => "projects#class_donut_chart"
      get "git_dates" => "git#dates"
      get "stats_line_chart" => "projects#stats_line_chart"
      get "smell_pie_chart" => "projects#smell_pie_chart"
      get "smell_klass_chart" => "projects#smell_klass_pie_chart"
    end
  end

  

end

app/views/shared/_commit_card.html.haml
.panel
  .row
    .col-lg-2.col-sm-2.text-center
      = gravatar_image_for_commit(commit.author_email)
    .col-lg-8.col-sm-7{style: "padding-left: 30px;"}
      %p
        Project:
        = commit.repository.project.title
      %p
        Commit:
        = commit.committed_at
      %p
        Author:
        = "#{commit.author_name} <#{commit.author_email}>"
      %p
        Commit ID: 
        = commit.commit_hash[0..15]
    .col-lg-2.col-sm-3
      - unless commit.report.nil?
        = link_to "Report", project_report_path(commit.repository.project, commit.report), class: "btn btn-primary"
      - else
        = link_to "Create", project_reports_path(commit.repository.project, hash: commit.commit_hash), class: "btn btn-warning", method: :post
    -# %li= commit.id
    -# %li= commit.author.name
    -#  gravatar_image_tag commit.author.email, class: "image-rounded"
    -# %li= commit.authored_date
    -# %li= commit.committed_date
    -# %li= commit.committer
    -# %li= commit.message
    -# %li= (commit.tree / 'Gemfile').data

app/views/shared/_navbar.html.haml
%nav.header.navbar.navbar-fixed-top.navbar-inverse
  %a.navbar-brand{href: "/"} 
    %img{src: "/images/logo.png", style: "width: 35px;"} 
    Putne
  %ul.nav.navbar-nav
    -#%li= link_to "Projects", projects_path if signed_in?
    - if signed_in?
      %li= link_to "Dash board", root_path if signed_in?
    %li= link_to "Help", help_path
    %li= link_to "About Putne", "http://putne.lapisan.com"
  - unless user_signed_in?
    -#= login_form_for_header
  - else
    .pull-right
      %a{href: destroy_user_session_path, "data-method" => "delete"}
        %button.btn.btn-danger.navbar-btn.pull-right{type: "button"} Sign out
      %ul.nav.navbar-nav.pull-right{style: "margin-right: 25px"}
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            = gravatar_image_for_navbar
            = current_user.email
            %span.caret
          %ul.dropdown-menu.navbar-profile
            .text-center.gravatar-profile
              = gravatar_image_for_profile
            %li.divider
            %li
              %a{href: "#"} Profile
            %li
              = link_to "New project", new_project_path
            %li
              %a{href: "#"} Account
            %li 
              = link_to "API Key", user_secret_key_path(user_id: current_user.id)
            %li.divider
            - if current_user.has_role?(:admin)
              %li
                = link_to "Rails admin", rails_admin_path
              %li
                = link_to "Sidekiq report", sidekiq_web_path

            
            

app/views/shared/_proect_card.html.haml
.panel-heading
.panel-body
.list-group

app/views/shared/_project_card.html.haml
%h3= link_to project.title, project_path(project.id), class: "list-group-item"
.list-group-item
  .row
    .col-lg-7.col-mg-7.col-sm-7
      %h5 Summary
    .col-lg-5.col-mg-5.col-sm-5
      %h5 Complexity
.list-group-item
  .row
    .col-lg-7.col-mg-7.col-sm-7
      = render partial: "report_module/project_summary_4", locals: {project: project, report: project.latest_report}      
    -# .col-lg-4.col-mg-4.col-sm-4
    -#   = render partial: "report_module/project_activity_4", locals: {project: project}      
    .col-lg-5.col-mg-5.col-sm-5
      %div{id: "#{project.title}-class-donut"}
      #code-smell-line-chart
      #language-stacked-area-chart
      -#= render partial: "report_module/project_complexity_chart_4", locals: {project: project}      
      .report-module
        .text-center
          -# %img{src: "/images/donut_chart.png", style: "width: 60%;"}

:javascript
  $(function(){
    d3_donut_chart("##{ project.title + "-class-donut"}", "#{project_graph_class_donut_chart_path(project_id: project)}")
  });

app/views/shared/_project_info.html.haml
.info
  .address
    %i.icon-folder-open
    = current_user.nickname
    = " / "
    - unless @project.homepage.nil?
      = link_to @project.homepage do
        %i.icon-home
        = @project.title
    - else
      = @project.title
    = " / "
    .btn-group
      %button.btn.btn-default.dropdown-toggle{type: "button", "data-toggle" => "dropdown"} 
        master
        %span.caret
    = " / "
    .btn-group
      %button.btn.btn-default.dropdown-toggle{type: "button", "data-toggle" => "dropdown"}
        = @report_type.nil? ? "Reports" : @report_type
        %span.caret
      %ul.dropdown-menu
        %li
          %a Complexities
        %li
          %a Duplications
        %li
          %a Code Smells
        %li
          %a Classes
        %li
          %a Methods
    = " / "
    - unless @project.reports.empty?
      .btn-group
        - commit_id = @project.reports[-1].commit.commit_hash[0..8]
        %button.btn.btn-default.dropdown-toggle{type: "button", "data-toggle" => "dropdown"}
          = @current_commit_id.nil? ? commit_id : @current_commit_id
          %span.caret
        %ul.dropdown-menu
          - @project.reports.each do |report|
            %li
              %a= report.commit.commit_hash[0..8]
      (-x commits)
      to latest commit
%br/

app/views/shared/_project_main_layout.html.haml
.project-body.col-lg-9.col-sm-9
  = current_user.email
  = " / "
  = @project.title
  = " / master"

app/views/shared/_project_sidebar.html.haml
-# .panel.panel-default
-#   .panel-heading Time machine
-#   .panel-body
-#     ID: 
-#     = params[:report_id]
-#     %br/
-#     Hash:
-#     -#= @report.commit.commit_hash[0..15]
-#     \..
%ul.nav.nav-pills.nav-stacked{style: "margin-top: 20px;"}
  - if @project.repository.valida?
    %ul.nav.nav-pills.nav-stacked
      %li
        = link_to project_url(@project) do
          -# %span.badge.pull-right#synopsis-help ?
          %span.badge.pull-right
          %i.icon-film
          Project summary
      %li
        = link_to project_reports_url(@project) do
          -# %span.badge.pull-right#report-help ?
          %span.badge.pull-right= @project.reports.count
          %i.icon-bar-chart
          Reports
      -# %li
      -#   = link_to project_commits_url(@project) do
      -#     -#- %span.badge.pull-right#files-help ?
      -#     %span.badge.pull-right= @report.commit_stat
      -#     %i.icon-list-alt
      -#     Activities
      -# %li
      -#   = link_to project_committers_url(@project) do
      -#     %i.icon-group
      -#     Committers
      -# %li
      -#   = link_to project_report_timeline_url(@project, @report) do
      -#     -# %span.badge.pull-right#timeline-help ?
      -#     %span.badge.pull-right
      -#     %i.icon-calendar
      -#     Timeline
      %hr
      -# %li
      -#   = link_to project_report_url(@project, @report) do
      -#     -# %span.badge.pull-right#synopsis-help ?
      -#     %span.badge.pull-right
      -#     %i.icon-film
      -#     Current report
      -# %br/
      %li
        = link_to project_report_classes_url(@project, @report) do
          -# %span.badge.pull-right#classes-help ?
          %span.badge.pull-right= @report.class_stat
          %i.icon-inbox
          Classes
      -# %li
        -# = link_to project_report_methods_url(@project, @report) do
        -#   -# %span.badge.pull-right#methods-help ?
        -#   %span.badge.pull-right= @report.method_stat
        -#   %i.icon-code
        -#   Methods
      %br/


      %li
        = link_to project_report_complexity_url(@project, @report) do
          -# %span.badge.pull-right#complexity-help ?
          %span.badge.pull-right= @report.complexity_stat
          %i.icon-superscript
          Complexities
      %li
        = link_to project_report_smells_url(@project, @report) do
          -# %span.badge.pull-right#smells-help ?
          %span.badge.pull-right= @report.smell_stat
          %i.icon-bug
          Smells
      %li
        = link_to project_report_duplicity_url(@project, @report) do
          -# %span.badge.pull-right#duplicity-help ?
          %span.badge.pull-right= @report.duplication_stat
          %i.icon-copy
          Duplications
      %li
        = link_to project_report_churn_url(@project, @report) do
          -# %span.badge.pull-right#churn-help ?
          %span.badge.pull-right= @report.churn_stat
          %i.icon-th
          Churns

      %hr
      -# %li
      -#   = link_to project_report_branches_url(@project, @report) do
      -#     %span.badge.pull-right#files-help ?
      -#     %span.badge.pull-right= @report.branche_stat
      -#     Branches

      -# %li
      -#   = link_to project_report_files_url(@project, @report) do
      -#     -# %span.badge.pull-right#files-help ?
      -#     %span.badge.pull-right= @report.file_stat
      -#     %i.icon-file
      -#     Files
  - else
    %li
      Your repository not valid.
  %li
    = link_to @project.repository.repository_url do
      -# %span.badge.pull-right#repository-help ?
      %span.badge.pull-right
      %i.icon-github-alt
      Repository
  %li
    = link_to project_settings_path(project_id: @project.id) do
      -# %span.badge.pull-right#settings-help ?
      %span.badge.pull-right
      %i.icon-wrench
      Settings