config/routes.rb
require 'sidekiq/web'

Putne::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Sidekiq::Web, at: "/sidekiq"
  devise_for :users

  root "main#index"
  get "help" => "main#help"

  resources :users do
    get "secret_key" => "secret_key#index"
    post "secret_key/reset"
  end

  resources :projects do
    post "api/hook" => "commit_hook#hook"
    get "api/hook_url" => "commit_hook#hook_url"
    get "branches" => "git#branches"
    get "commits" => "git#commits"
    get "committers" => "git#committers"
    get "settings"
    get "create_all_reports"

    resources :reports do
      get "files" => "metrics#files"
      get "file" => "metrics#file"
      
      get "classes" => "metrics#classes"
      get "klass" => "metrics#klass"
      get "klass/:class_id" => "metrics#klass"

      get "methods" => "metrics#methods"
      get "method" => "metrics#method"

      get "churn" => "metrics#churn"
      get "complexity" => "metrics#complexity"
      get "duplicity" => "metrics#duplicity"
      get "smells" => "metrics#smells"
      get "smell" => "metrics#smell"

      get "timeline" => "metrics#timeline"
    end

    namespace :graph do
      get "sunburst_chart" => "projects#sunburst_chart"
      get "class_donut_chart" => "projects#class_donut_chart"
      get "git_dates" => "git#dates"
      get "stats_line_chart" => "projects#stats_line_chart"
      get "smell_pie_chart" => "projects#smell_pie_chart"
      get "smell_klass_chart" => "projects#smell_klass_pie_chart"
    end
  end

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :reports, dependent: :destroy
  has_one :repository, dependent: :destroy

  validates_presence_of :user_id, :title
  accepts_nested_attributes_for :repository
  acts_as_taggable

  def reports_by_day
    reports.includes(:commit).to_a.uniq{ |report| report.commit.committed_at.strftime("%Y%m%d")}
  end

  def latest_report
    reports.includes(:commit).to_a.uniq{ |report| report.commit.committed_at.strftime("%Y%m%d")}[-1]
  end
end

app/controllers/graph/projects_controller.rb
class Graph::ProjectsController < ApplicationController
  def sunburst_chart
    project = Project.find(params[:project_id]).decorate
    render :json => {name: project.title, children: project.flog_scores_for_two_level_sunburst_data }
  end

  def class_donut_chart
    project = Project.find(params[:project_id]).decorate
    text = CSV.generate do |csv|
      csv << %w(Category Data)
      text = project.flog_scores_for_klass_donut_data.each { |complexity| csv << [complexity[:name], complexity[:size]] }
    end
    
    render text: text, content_type: 'text/html'
  end

  def smell_pie_chart
    project = Project.find(params[:project_id]).decorate
    text = CSV.generate do |csv|
      csv << %w(Category Data)
      text = project.smell_count_by_smell_data.each { |data| csv << [data[:name], data[:count]] }
    end
    
    render text: text, content_type: 'text/html'
  end

    def smell_klass_pie_chart
    project = Project.find(params[:project_id]).decorate
    text = CSV.generate do |csv|
      csv << %w(Category Data)
      text = project.smell_count_by_klass_data.each { |data| csv << [data[:name], data[:count]] }
    end
    
    render text: text, content_type: 'text/html'
  end
  
  def stats_line_chart
    project = Project.find(params[:project_id]).decorate
    columns = params[:columns].nil? ? %w(date Complexity Duplication Smell Churn) : params[:columns].split(",")
    
    text = CSV.generate(col_sep: "\t") do |csv|
      csv << columns
      text = project.stats_line_data.each do |stats|
        data = []
        columns.each {|column| data << stats[column.downcase.to_sym] }
        csv << data
      end
    end
    
    render text: text, content_type: 'text/html'
    
    # churn, complexity, duplication, smell, commit, branches, file,
    # classes, methods
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  layout "layouts/sidebar", only: [:show, :settings]
  #before_action :protect_from_forgery, except: :commit_hook

  # GET /projects
  # GET /projects.json
  def index
    redirect_to root_url
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id]).decorate
    @title = "Project - #{@project.title}"
    @report = @project.latest_report
  end

  # GET /projects/new
  def new
    @title = "New project"
    @project = Project.new
    @project.repository = Repository.new
  end

  # GET /projects/1/edit
  def edit
    
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.create(project_params)
    # @project.repository = Repository.last #Repository.create!(params[:project][:repository_attributes])
    InitRepositoryWorker.perform_async(@project.repository.id)
    in_time = 120
    
    @project.repository.commits.each do |commit|
      if Report.find_by(commit_id: commit.id.to_s).nil?
        ReportWorker.perform_in in_time, @project.repository.id, commit.commit_hash
        in_time += 120
      end
    end
    
    respond_to do |format|
      if @project.id?
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_all_reports
    @project = Project.find params[:project_id]
    in_time = 5

    @project.repository.register_recent_commits(200)
    @project.repository.commits.each do |commit|
      if Report.find_by(commit_id: commit.id.to_s).nil?
        ReportWorker.perform_in in_time, @project.repository.id, commit.commit_hash
        in_time += 120
      end
    end

    redirect_to projects_path
  end
  
  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json #{ head :no_content} 
      else
        format.html #{ render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def settings
    @project = Project.find params[:project_id]
    @title = "Project - #{@project.title}"
    @report = @project.reports.sort { |report| report.commit.committed_at }[-1]
  end

  def commit_hook
    @project = Project.find params[:project_id]
    key = @project.user.secret_key.key
    ReportWorker.perform_async @project.repository.id, params[:hash] if params[:ci_key] == key

    respond_to do |format|
      if @project.id?
        format.html { render text: "aoeuaeou" }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end

  end

  def commit_hook_url
    @project = Project.find params[:project_id]
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :language, :user_id,
                                      repository_attributes: [:repository_url, :repository_type]
                                      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  = f.simple_fields_for :repository do |r|
    = f.hidden_field :user_id, value: current_user.id
    = f.hidden_field :language, value: "ruby"
    .form-group= f.input :title, label: "프로젝트 이름", input_html: {class: "form-control", placeholder: "Title"}
    .form-group= f.input :description, label: "프로젝트 설명", input_html: {class: "form-control", style: "height: 250px;", placeholder: "Description"}
    .form-group= r.input :repository_url, label: "버전관리 저장소 URL(Git)", as: "string", input_html: {class: "form-control", placeholder: "Repository"} 
    = r.hidden_field :repository_type, value: "git"
  
  %br/
  .actions
    = f.button :submit, class: "btn btn-info"

app/views/projects/_show.html.haml
.list-group
  .list-group-item
    .row
      .col-lg-4.col-mg-4.col-sm-4
        = render partial: "report_module/project_summary_4", locals: { project: project, report: project.latest_report }      
      -#   %br/
      -#   = render partial: "report_module/project_hotspot_4", locals: { report: project.latest_report }
      .col-lg-8.col-mg-8.col-sm-8
        = render partial: "report_module/project_sunburst", locals: { project: project }

  %h4.list-group-item Commit trend
  .list-group-item
    .row
      -# .col-lg-4.col-mg-4.col-sm-4
      -#   = render partial: "report_module/project_activity_4", locals: {project: project}      
      .col-lg-12.col-mg-12.col-sm-12
        #commit-trend-calendar-chart
        -#%img{src: "/images/stacked_bar_chart.png", style: "width: 100%; height: 250px;"}

  %h4.list-group-item Code quality timeline
  .list-group-item
    .row
      -# .col-lg-4.col-mg-4.col-sm-4
      -#   = render partial: "report_module/project_summary_4", locals: { project: project, report: project.latest_report}      
      .col-lg-12.col-mg-12.col-sm-12
        #code-quality-line-chart
        -#%img{src: "/images/line_chart.jpg", style: "width: 100%; height: 250px;"}

  %h4.list-group-item Class Complexity timeline
  .list-group-item
    .row
      .col-lg-4.col-mg-4.col-sm-4
        = render partial: "report_module/project_complexity_4", locals: {project: project}      
      .col-lg-8.col-mg-8.col-sm-8
        #class-complexity-line-chart

  %h4.list-group-item Code smell timeline
  .list-group-item
    .row
      .col-lg-4.col-mg-4.col-sm-4
        = render partial: "report_module/project_smell_4", locals: {project: project}      
      .col-lg-8.col-mg-8.col-sm-8
        #code-smell-line-chart

  -# %h4.list-group-item Language
  -# .list-group-item
  -#   .row
  -#     .col-lg-4.col-mg-4.col-sm-4
  -#       = render partial: "report_module/project_language_4", locals: {project: project}      
  -#     .col-lg-8.col-mg-8.col-sm-8
  -#       #language-stacked-area-chart
  -#       -#%img{src: "/images/stacked_area_chart.png", style: "width: 100%; height: 250px;"}

:javascript
  $(function(){
    //d3_sunburst_chart("#project-sunburst");
    d3_calendar_chart("#commit-trend-calendar-chart", "#{project_graph_git_dates_path(project_id: @project)}");
    d3_multi_line_chart("#code-quality-line-chart", "#{project_graph_stats_line_chart_path(project_id: @project)}");
    //d3_multi_line_chart("#class-complexity-line-chart");
    //d3_multi_line_chart("#code-smell-line-chart");
  });

app/views/projects/commit_hook_url.html.haml
= link_to "link", project_commit_hook_url(ci_key: @project.user.secret_key.key, project_id: @project.id), method: "post"

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%br/
= link_to 'New project', new_project_path
%br/
%br/
%table.table.table-striped
  %tr
    %th Title
    %th Description
    %th Language
    %th Repository type
    %th Repository url

  - @projects.each do |project|
    %tr
      %td= link_to project.title, project
      %td= project.description
      %td= project.language
      %td= project.repository_type
      %td= project.repository_url
      -#%td= link_to 'Edit', edit_project_path(project)
      -#%td= link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/projects/new.html.haml
%h3
  새로운 프로젝트 만들기
  %span.label.label-danger Ruby
  %span.label.label-success Git
.col-lg-8.col-md-8.col-sm-8
  .container
    = render 'form'
.col-lg-4.col-md-4.col-sm-4
  .panel
    .panel-heading 
      %h4 새 프로젝트 만들기.
    .panel-body
      %p 이 페이지에서 새로운 Putne 프로젝트를 생성할 수 있습니다. 여러분의 Ruby 소스코드를 Putne에 등록하면 서버에서 자동적으로 코드의 변경사항을 확인하고, 코드의 품질을 측정해줍니다. 코드의 품질은 사람의 건강상태와 같습니다. 
      %p 잘 관리된 프로젝트일 수록 오랜 기간 개발에도 버틸 수 있으며 유지보수 또한 쉬워집니다. 
      %p.alert.alert-danger
        현재는 Ruby와 Git 저장소만을 지원합니다.

app/views/projects/settings.html.haml
.panel-heading
  %h1 Settings
.list-group
  .list-group-item
    %h3 Destroy project
  .list-group-item
    = link_to project_path(@project), method: "delete", confirm: "Are you sure?" do
      %button.btn.btn-danger Destroy
  .list-group-item
    %h3 Hook url
  .list-group-item
    = project_api_hook_url


 

app/views/projects/show.html.haml
.panel-heading
  %h1 
    %i.icon-film
    = @project.title
    Summary
- if @project.reports.count > 0
  = render partial: "show", locals: {project: @project}