config/routes.rb
require 'sidekiq/web'

Putne::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Sidekiq::Web, at: "/sidekiq"
  devise_for :users

  root "main#index"
  get "help" => "main#help"

  resources :users do
    get "secret_key" => "secret_key#index"
    post "secret_key/reset"
  end

  resources :projects do
    post "api/hook" => "commit_hook#hook"
    get "api/hook_url" => "commit_hook#hook_url"
    get "branches" => "git#branches"
    get "commits" => "git#commits"
    get "committers" => "git#committers"
    get "settings"
    get "create_all_reports"

    resources :reports do
      get "files" => "metrics#files"
      get "file" => "metrics#file"
      
      get "classes" => "metrics#classes"
      get "klass" => "metrics#klass"
      get "klass/:class_id" => "metrics#klass"

      get "methods" => "metrics#methods"
      get "method" => "metrics#method"

      get "churn" => "metrics#churn"
      get "complexity" => "metrics#complexity"
      get "duplicity" => "metrics#duplicity"
      get "smells" => "metrics#smells"
      get "smell" => "metrics#smell"

      get "timeline" => "metrics#timeline"
    end

    namespace :graph do
      get "sunburst_chart" => "projects#sunburst_chart"
      get "class_donut_chart" => "projects#class_donut_chart"
      get "git_dates" => "git#dates"
      get "stats_line_chart" => "projects#stats_line_chart"
      get "smell_pie_chart" => "projects#smell_pie_chart"
      get "smell_klass_chart" => "projects#smell_klass_pie_chart"
    end
  end

  

end

app/models/report.rb
class Report < ActiveRecord::Base
  include RegisterReport

  belongs_to :branch
  belongs_to :commit
  belongs_to :repository
  belongs_to :project
   
  has_many :target_files, dependent: :destroy
  has_many :target_classes, dependent: :destroy
  has_many :target_methods, dependent: :destroy
  has_many :scores, dependent: :destroy
  has_many :smells, dependent: :destroy

  has_many :duplications, dependent: :destroy
  
  validates_presence_of :project, :branch, :commit, :repository
  validates_uniqueness_of :commit

  default_scope -> { order("") }

  def input_stats
    update_attributes(churn_stat: sum_churns,
                      complexity_stat: sum_complexities,
                      duplication_stat: sum_duplications,
                      smell_stat: sum_smells,
                      commit_stat: sum_commits,
                      branche_stat: sum_branches,
                      file_stat: sum_files,
                      class_stat: sum_classes,
                      method_stat: sum_methods
                      )
  end

  def sum_churns
    scores.churns.sum(:score)
  end

  def sum_complexities
    scores.flogs.type_method.sum(:score)
  end

  def sum_duplications
    duplications.count
  end

  def sum_smells
    smells.reeks.count
  end

  def sum_branches
    repository.git.branches.count
  end
  
  def sum_commits
    repository.git.commit_stats.count
  end

  def sum_files
    target_files.count
  end

  def sum_classes
    target_classes.count
  end

  def sum_methods
    target_methods.count
  end

  def flog_scores
    target_classes.map { |klass| {name: klass.name, size: klass.scores.flogs[0].score, path: klass.target_file.path } }
      .delete_if { |hash| hash[:size] == 0} 
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  load_and_authorize_resource class: Report
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  layout "layouts/sidebar"

  # GET /reports
  # GET /reports.json
  def index
    @project = Project.find params[:project_id]
    @reports = @project.reports.page(params[:page]).per(15)
    #@report = @project.reports.sort { |report| report.commit.committed_at }[-1]
    @report = @project.reports[-1]
    @graphs = []

    # @graphs << ReportSummaryTimeSeries.new(@reports, "Method", "#ff0000") { |report| report.method_stat }
    # @graphs << ReportSummaryTimeSeries.new(@reports, "Commit", "#0000ff") { |report| report.commit_stat }
    # @graphs << ReportSummaryTimeSeries.new(@reports, "Smell", "#00ff00") { |report| report.smell_stat }
    # @graphs << ReportSummaryTimeSeries.new(@reports, "Complexity", "#da329e") { |report| report.complexity_stat / 10}
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @project = Project.find params[:project_id]
    @report = Report.find params[:id]
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @project = Project.find params[:project_id]
    ReportWorker.perform_async @project.repository.id, params[:hash]
    redirect_to :back
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:repository_id, :branch_id, :commit_id, :project_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= simple_form_for(@report) do |f|
  = f.error_notification

  .inputs
    = f.input :repository_id
    = f.input :branch_id
    = f.input :commit_id
    = f.input :project_id

  .actions
    = f.button :submit

app/views/reports/edit.html.haml
%h1 Editing report

= render 'form'

= link_to 'Show', @report
\|
= link_to 'Back', reports_path

app/views/reports/index.html.haml
-#%svg#reports-summary-graph{style: "height: 300px;"}
.panel-heading
  %h1 
    %i.icon-bar-chart
    = @project.title
.list-group-item
  -#%img{src: "/images/line_chart.jpg", style: "height: 300px;width: 100%;"}
  .row
    .col-lg-12.col-mg-12.col-sm-12
      #code-quality-line-chart

%table.table.table-striped
  %th At
  -#%th Commit
  %th Class
  %th Methods
  %th Churn
  %th Complex
  %th Smell
  - @reports.each do |report|
    %tr
      -#%td= 
      %td= link_to report.commit.committed_at, project_report_path(report.project, report)
      -#%td= report.commit_stat
      %td= report.class_stat
      %td= report.method_stat
      %td= report.churn_stat
      %td= report.complexity_stat
      %td= report.smell_stat
= paginate(@reports)

:javascript
  $(function(){
    d3_multi_line_chart("#code-quality-line-chart", "#{project_graph_stats_line_chart_path(project_id: @project)}");
  });

app/views/reports/new.html.haml
%h1 New report

= render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.haml
.panel-heading
  %h1 
    %i.icon-film
    = @project.title
    Summary
.list-group
  .list-group-item
    .row
      .col-lg-4.col-mg-4.col-sm-4
        = render partial: "report_module/project_summary_4", locals: {project: @project}      
        %br/
        = render partial: "report_module/project_hotspot_4", locals: {project: @project}
      .col-lg-8.col-mg-8.col-sm-8
        %img{src: "/images/sunbrust.jpg", style: "width: 100%"}